name: Check version bump
on:
  pull_request:
    branches: [main]
jobs:
  check:
    name: Check version bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust toolchain stable-x86_64-unknown-linux-gnu for ubuntu-latest
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-unknown-linux-gnu
          override: true
      - name: Read branch version
        id: branch_version
        run: echo "version=$(cargo read-manifest | jq -r .version)" >> $GITHUB_OUTPUT
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Read main version
        id: main_version
        run: echo "version=$(cargo read-manifest | jq -r .version)" >> $GITHUB_OUTPUT
      - name: Check version bump
        run: |
          if [ "${{ steps.branch_version.outputs.version }}" == "${{ steps.main_version.outputs.version }}" ]; then
            echo "Missing version bump!"
            exit 1
          else
            echo "Version was bumped!"
          fi
